### ISSUE TITLE
Bulleted Lists overlapping

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/moodle#17]
Noticed this in number 4 here: https://place.fi.ncsu.edu/mod/page/view.php?id=3950. Looks to be an issue with the CSS and in line conflicting.

![screen shot 2017-03-21 at 3 45 14 pm](https://cloud.githubusercontent.com/assets/13201528/24167592/a851461c-0e4d-11e7-846a-c4da5327f623.png)

**Comment by mjsamberg** [comment]
This issue was moved to TheFridayInstitute/moodle-theme_fridayinstitute#9
